"""create conversations and messages tables

Revision ID: 1932f3e421c3
Revises: 002_create_users
Create Date: 2026-01-23 01:29:48.046426

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1932f3e421c3'
down_revision: Union[str, None] = '002_create_users'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('playing_with_neon')
    op.drop_column('messages', 'content')
    op.drop_column('messages', 'role')
    op.alter_column('tasks', 'description',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(length=2000),
               existing_nullable=True)
    op.alter_column('tasks', 'completed',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('tasks', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('tasks', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=False)
    op.drop_index(op.f('idx_tasks_user_created'), table_name='tasks')
    op.drop_index(op.f('idx_tasks_user_id'), table_name='tasks')
    op.create_index(op.f('ix_tasks_user_id'), 'tasks', ['user_id'], unique=False)
    op.drop_constraint(op.f('fk_tasks_user_id'), 'tasks', type_='foreignkey')
    op.create_foreign_key(None, 'tasks', 'users', ['user_id'], ['id'])
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=False)
    op.drop_index(op.f('idx_users_email'), table_name='users')
    op.drop_index(op.f('idx_users_username'), table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index(op.f('idx_users_username'), 'users', ['username'], unique=True)
    op.create_index(op.f('idx_users_email'), 'users', [sa.literal_column('lower(email::text)')], unique=True)
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=False)
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=False)
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.create_foreign_key(op.f('fk_tasks_user_id'), 'tasks', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_tasks_user_id'), table_name='tasks')
    op.create_index(op.f('idx_tasks_user_id'), 'tasks', ['user_id'], unique=False)
    op.create_index(op.f('idx_tasks_user_created'), 'tasks', ['user_id', sa.literal_column('created_at DESC')], unique=False)
    op.alter_column('tasks', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=False)
    op.alter_column('tasks', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=False)
    op.alter_column('tasks', 'completed',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('tasks', 'description',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=2000),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.add_column('messages', sa.Column('role', sa.VARCHAR(length=10), autoincrement=False, nullable=False))
    op.add_column('messages', sa.Column('content', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.create_table('playing_with_neon',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('value', sa.REAL(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('playing_with_neon_pkey'))
    )
    # ### end Alembic commands ###
